In [31]:
import pandas as pd
import numpy as np
import math

In [13]:
df_2009 = pd.read_excel("SDOH_2009_COUNTY_1_0.xlsx", sheet_name = 1)

In [16]:
df = df_2009

In [17]:
#not including 2018 (website mentions 2018's incorrect data)
for year in range (2010, 2018):
    df = df.append(pd.read_excel("SDOH_" + str(year) + "_COUNTY_1_0.xlsx", sheet_name = 1))
df = df.append (pd.read_excel("SDOH_2019_COUNTY_1_0.xlsx", sheet_name = 1))

In [18]:
df

,YEAR,COUNTYFIPS,STATEFIPS,STATE,COUNTY,REGION,TERRITORY,ACS_TOT_POP_WT,ACS_TOT_POP_US_ABOVE1,ACS_TOT_POP_ABOVE5,...,MMD_READM_OTHER_RATE,MMD_READM_ASIAN_RATE,MMD_READM_HISP_RATE,MMD_READM_AIAN_RATE,MMD_ANXIETY_DISD,MMD_BIPOLAR_DISD,MMD_DEPR_DISD,MMD_PERSONALITY_DISD,MMD_OUD_IND,MMD_THREE_OR_MORE_COND
0,2009,1001,1,Alabama,Autauga County,South,0,49584.0,48877.0,46182.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2009,1003,1,Alabama,Baldwin County,South,0,171997.0,169921.0,161266.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2009,1005,1,Alabama,Barbour County,South,0,29663.0,29271.0,27811.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2009,1007,1,Alabama,Bibb County,South,0,21464.0,21235.0,20178.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2009,1009,1,Alabama,Blount County,South,0,56804.0,56113.0,53064.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3227,2019,72151,72,Puerto Rico,Yabucoa Municipio,NaN,1,33499.0,NaN,32174.0,...,NaN,NaN,NaN,NaN,7.0,1.0,15.0,0.0,0.0,53.0
3228,2019,72153,72,Puerto Rico,Yauco Municipio,NaN,1,35428.0,NaN,33956.0,...,NaN,NaN,16.0,NaN,9.0,3.0,12.0,0.0,0.0,62.0
3229,2019,78010,78,US Virgin Islands,St. Croix,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3230,2019,78020,78,US Virgin Islands,St. John Island,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3231,2019,78030,78,US Virgin Islands,St. Thomas Island,NaN,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df[df['CDCA_HEART_DTH_RATE_ABOVE35'].isna()]['CDCA_HEART_DTH_RATE_ABOVE35']

71     NaN
76     NaN
86     NaN
87     NaN
89     NaN
        ..
3147   NaN
3150   NaN
3229   NaN
3230   NaN
3231   NaN
Name: CDCA_HEART_DTH_RATE_ABOVE35, Length: 183, dtype: float64

In [41]:
df_backup = df

In [42]:
for index, row in df_backup.iterrows():
    if (math.isnan(row['CDCA_HEART_DTH_RATE_ABOVE35'])):
        print(row['COUNTY'], row['YEAR'])
        df_backup = df_backup[df_backup.COUNTY != row['COUNTY']]

Bristol Bay Borough 2009
Hoonah-Angoon Census Area 2009
Petersburg Census Area 2009
Prince of Wales-Hyder Census Area 2009
Skagway Municipality 2009
Wade Hampton Census Area 2009
Wrangell City and Borough 2009
Yakutat City and Borough 2009
Kalawao County 2009
Shannon County 2009
Bedford city 2009
Eastern District 2009
Manu'a District 2009
Rose Island 2009
Swain's Island 2009
Western District 2009
Saipan Municipality 2009
St. Croix 2009
St. John Island 2009
St. Thomas Island 2009
Bristol Bay Borough 2010
Hoonah-Angoon Census Area 2010
Petersburg Census Area 2010
Prince of Wales-Hyder Census Area 2010
Skagway Municipality 2010
Wade Hampton Census Area 2010
Wrangell City and Borough 2010
Yakutat City and Borough 2010
Shannon County 2010
Bedford city 2010
Eastern District 2010
Manu'a District 2010
Rose Island 2010
Swain's Island 2010
Western District 2010
St. Croix 2010
St. John Island 2010
St. Thomas Island 2010
Bristol Bay Borough 2011
Hoonah-Angoon Census Area 2011
Petersburg Census Area 2011
Prince of Wales-Hyder Census Area 2011
Skagway Municipality 2011
Wade Hampton Census Area 2011
Wrangell City and Borough 2011
Yakutat City and Borough 2011
Shannon County 2011
Bedford city 2011
Eastern District 2011
Manu'a District 2011
Rose Island 2011
Swain's Island 2011
Western District 2011
Rota 2011
Saipan Municipality 2011
Tinian Municipality 2011
St. Croix 2011
St. John Island 2011
St. Thomas Island 2011
Bristol Bay Borough 2012
Hoonah-Angoon Census Area 2012
Petersburg Census Area 2012
Prince of Wales-Hyder Census Area 2012
Skagway Municipality 2012
Wade Hampton Census Area 2012
Wrangell City and Borough 2012
Yakutat City and Borough 2012
Shannon County 2012
King County 2012
Bedford city 2012
Eastern District 2012
Manu'a District 2012
Rose Island 2012
Swain's Island 2012
Western District 2012
Rota 2012
Saipan Municipality 2012
Tinian Municipality 2012
St. Croix 2012
St. John Island 2012
St. Thomas Island 2012
Bristol Bay Borough 2013
Hoonah-Angoon Census Area 2013
Petersburg Census Area 2013
Prince of Wales-Hyder Census Area 2013
Skagway Municipality 2013
Wade Hampton Census Area 2013
Wrangell City and Borough 2013
Yakutat City and Borough 2013
Shannon County 2013
Bedford city 2013
Eastern District 2013
Manu'a District 2013
Rose Island 2013
Swain's Island 2013
Western District 2013
Rota 2013
Saipan Municipality 2013
Tinian Municipality 2013
St. Croix 2013
St. John Island 2013
St. Thomas Island 2013
Bristol Bay Borough 2014
Hoonah-Angoon Census Area 2014
Petersburg Census Area 2014
Prince of Wales-Hyder Census Area 2014
Skagway Municipality 2014
Wade Hampton Census Area 2014
Wrangell City and Borough 2014
Yakutat City and Borough 2014
Shannon County 2014
Eastern District 2014
Manu'a District 2014
Rose Island 2014
Swain's Island 2014
Western District 2014
Rota 2014
Saipan Municipality 2014
Tinian Municipality 2014
St. Croix 2014
St. John Island 2014
St. Thomas Island 2014
Bristol Bay Borough 2015
Hoonah-Angoon Census Area 2015
Kusilvak Census Area 2015
Petersburg Census Area 2015
Prince of Wales-Hyder Census Area 2015
Skagway Municipality 2015
Wrangell City and Borough 2015
Yakutat City and Borough 2015
Oglala Lakota County 2015
Eastern District 2015
Manu'a District 2015
Rose Island 2015
Swain's Island 2015
Western District 2015
Rota 2015
Saipan Municipality 2015
Tinian Municipality 2015
St. Croix 2015
St. John Island 2015
St. Thomas Island 2015
Bristol Bay Borough 2016
Hoonah-Angoon Census Area 2016
Kusilvak Census Area 2016
Petersburg Census Area 2016
Prince of Wales-Hyder Census Area 2016
Skagway Municipality 2016
Wrangell City and Borough 2016
Yakutat City and Borough 2016
Oglala Lakota County 2016
Eastern District 2016
Manu'a District 2016
Rose Island 2016
Swain's Island 2016
Western District 2016
Saipan Municipality 2016
St. Croix 2016
St. John Island 2016
St. Thomas Island 2016
Bristol Bay Borough 2017
Yakutat City and Borough 2017
Eastern District 2017
Manu'a District 2017
Rose Island 2017
Swain's Island 2017
Western District 2017
Saipan Municipality 2017
St. Croix 2017
St. John Island 2017
St. Thomas Island 2017
Bristol Bay Borough 2019
Skagway Municipality 2019
Yakutat City and Borough 2019
Eastern District 2019
Manu'a District 2019
Rose Island 2019
Swain's Island 2019
Western District 2019
Saipan Municipality 2019
St. Croix 2019
St. John Island 2019
St. Thomas Island 2019

In [43]:
df_backup[df_backup['CDCA_HEART_DTH_RATE_ABOVE35'].isna()]['CDCA_HEART_DTH_RATE_ABOVE35']

Series([], Name: CDCA_HEART_DTH_RATE_ABOVE35, dtype: float64)

In [46]:
df_backup[df_backup['COUNTY'] == "Petersburg Census Area"]

Empty DataFrame
Columns: [YEAR, COUNTYFIPS, STATEFIPS, STATE, COUNTY, REGION, TERRITORY, ACS_TOT_POP_WT, ACS_TOT_POP_US_ABOVE1, ACS_TOT_POP_ABOVE5, ACS_TOT_POP_ABOVE15, ACS_TOT_POP_ABOVE16, ACS_TOT_POP_16_19, ACS_TOT_POP_ABOVE25, ACS_TOT_CIVIL_POP_ABOVE18, ACS_TOT_CIVIL_VET_POP_ABOVE25, ACS_TOT_OWN_CHILD_BELOW17, ACS_TOT_WORKER_NWFH, ACS_TOT_WORKER_HH, ACS_TOT_CIVILIAN_LABOR, ACS_TOT_CIVIL_EMPLOY_POP, ACS_TOT_POP_POV, ACS_TOT_GRANDCHILDREN_GP, ACS_TOT_HU, ACS_TOT_HH, ACS_AVG_HH_SIZE, ACS_TOT_CIVIL_VET_POP, ACS_PCT_MALE, ACS_PCT_FEMALE, ACS_PCT_CTZ_US_BORN, ACS_PCT_CTZ_NONUS_BORN, ACS_PCT_FOREIGN_BORN, ACS_PCT_NON_CITIZEN, ACS_PCT_CTZ_NATURALIZED, ACS_PCT_NONCTN_1990, ACS_PCT_NONCTN_1999, ACS_PCT_NONCTN_2000, ACS_PCT_API_LANG, ACS_PCT_ENGL_NOT_ALL, ACS_PCT_ENGL_NOT_WELL, ACS_PCT_ENGL_VERY_WELL, ACS_PCT_ENGL_WELL, ACS_PCT_ENGLISH, ACS_PCT_HH_LIMIT_ENGLISH, ACS_PCT_OTH_EURP, ACS_PCT_OTH_LANG, ACS_PCT_SPANISH, ACS_PCT_VET, ACS_PCT_GULFWAR_1990_2001, ACS_PCT_GULFWAR_2001, ACS_PCT_GULFWAR_VIETNAM, ACS_PCT_VIETNAM, ACS_MEDIAN_AGE, ACS_MEDIAN_AGE_MALE, ACS_MEDIAN_AGE_FEMALE, ACS_PCT_AGE_0_4, ACS_PCT_AGE_5_9, ACS_PCT_AGE_10_14, ACS_PCT_AGE_15_17, ACS_PCT_AGE_0_17, ACS_PCT_AGE_18_29, ACS_PCT_AGE_18_44, ACS_PCT_AGE_30_44, ACS_PCT_AGE_45_64, ACS_PCT_AGE_50_64, ACS_PCT_AGE_ABOVE65, ACS_PCT_AGE_ABOVE80, ACS_PCT_AIAN, ACS_PCT_AIAN_FEMALE, ACS_PCT_AIAN_MALE, ACS_PCT_AIAN_NONHISP, ACS_PCT_ASIAN, ACS_PCT_ASIAN_FEMALE, ACS_PCT_ASIAN_MALE, ACS_PCT_ASIAN_NONHISP, ACS_PCT_BLACK, ACS_PCT_BLACK_FEMALE, ACS_PCT_BLACK_MALE, ACS_PCT_BLACK_NONHISP, ACS_PCT_HISP_FEMALE, ACS_PCT_HISP_MALE, ACS_PCT_HISPANIC, ACS_PCT_MULT_RACE, ACS_PCT_MULT_RACE_FEMALE, ACS_PCT_MULT_RACE_MALE, ACS_PCT_MULT_RACE_NONHISP, ACS_PCT_NHPI, ACS_PCT_NHPI_FEMALE, ACS_PCT_NHPI_MALE, ACS_PCT_NHPI_NONHISP, ACS_PCT_OTHER_FEMALE, ACS_PCT_OTHER_MALE, ACS_PCT_OTHER_NONHISP, ACS_PCT_OTHER_RACE, ACS_PCT_WHITE, ACS_PCT_WHITE_FEMALE, ACS_PCT_WHITE_MALE, ACS_PCT_WHITE_NONHISP, ACS_PCT_HOUSEHOLDER_WHITE, ACS_PCT_HOUSEHOLDER_BLACK, ...]
Index: []

[0 rows x 1297 columns]

In [47]:
df = df_backup

In [48]:
df.to_csv('Combined_AHRQ_Data.csv')